image: "rust:latest"

stages:
  - build
  - test
  - publish

variables:
  GITLAB_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  APP_USER_IDS: $USER_IDS
  APP_USER_TOKENS: $USER_TOKENS
  APP_URL: $GITLAB_URL
  APP_DATE_DEPTH: $DATE_DEPTH
  APP_PER_PAGE: $PER_PAGE_LIMIT

default:
  before_script:
    - rustc --version
    - cargo --version
    - cd projects

build:
  stage: build
  script:
    - cargo build
    - cargo build --examples
  only:
    - merge_requests

test:
  stage: test
  script:
    - cargo test
  only:
    - merge_requests

clippy:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --version
    - cargo clippy -- -D warnings
  only:
    - merge_requests

format:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
  only:
    - merge_requests

lines_of_code:
  stage: publish
  script:
    - cd .. 
    - cargo install --git https://github.com/XAMPPRocky/tokei.git tokei
    - tokei .
  only:
    - main
