[package]
name = "hw-006"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
clap = { version = "4.0.29", features = ["derive"] }
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_json = "1.0"